function findMissing(arr1, arr2) {
    const set1 = new Set(arr1);
    const set2 = new Set(arr2);

    const missingFromArr2 = arr1.filter(item => !set2.has(item));
    const missingFromArr1 = arr2.filter(item => !set1.has(item));

    return {
        missingFromArr2,
        missingFromArr1
    };
};

const FAcitiesO = [
    'Alexander City',
    'Andalusia',
    'Anniston',
    'Athens',
    'Atmore',
    'Auburn',
    'Bessemer',
    'Birmingham',
    'Chickasaw',
    'Clanton',
    'Cullman',
    'Decatur',
    'Demopolis',
    'Dothan',
    'Enterprise',
    'Eufaula',
    'Florence',
    'Fort Payne',
    'Gadsden',
    'Greenville',
    'Guntersville',
    'Huntsville',
    'Jasper',
    'Marion',
    'Mobile',
    'Montgomery',
    'Opelika',
    'Ozark',
    'Phenix City',
    'Prichard',
    'Scottsboro',
    'Selma',
    'Sheffield',
    'Sylacauga',
    'Talladega',
    'Troy',
    'Tuscaloosa',
    'Tuscumbia',
    'Tuskegee',
];

const googleCitiesO = [
    "Birmingham",
    "Montgomery",
    "Mobile",
    "Huntsville",
    "Tuscaloosa",
    "Hoover",
    "Dothan",
    "Auburn",
    "Decatur",
    "Madison",
    "Florence",
    "Phenix City",
    "Gadsden",
    "Prattville",
    "Vestavia Hills",
    "Alabaster",
    "Opelika",
    "Enterprise",
    "Bessemer",
    "Daphne",
    "Homewood",
    "Northport",
    "Anniston",
    "Prichard",
    "Athens",
    "Pelham",
    "Oxford",
    "Albertville",
    "Selma",
    "Mountain Brook",
    "Trussville",
    "Troy",
    "Center Point",
    "Hueytown",
    "Millbrook",
    "Helena",
    "Fairhope",
    "Ozark",
    "Cullman",
    "Gardendale",
    "Foley",
    "Talladega",
    "Sylacauga",
    "Jasper",
    "Hartselle",
    "Alexander City",
    "Muscle Shoals",
    "Scottsboro",
    "Eufaula",
    "Fultondale",
    "Irondale",
    "Lanett",
    "Moody",
    "Leeds",
    "Fairfield",
    "Fort Payne",
    "Chelsea",
    "Saraland",
    "Clanton",
    "Rainbow City",
    "Daleville",
    "Satsuma",
    "Greenville",
    "Monroeville",
    "Jacksonville",
    "Tallassee",
    "Hokes Bluff",
    "Brent",
    "Arab",
    "Boaz",
    "Rainsville",
    "Tuscumbia",
    "Childersburg",
    "Bay Minette",
    "Andalusia",
    "Demopolis",
    "Oneonta",
    "Evergreen",
    "Gulf Shores",
    "Union Springs",
    "Thomasville",
    "Red Bay",
    "Attalla",
    "LaFayette",
    "Livingston",
    "Piedmont",
    "Hamilton",
    "Hartford",
    "Headland",
    "Ashland",
    "Geneva",
    "Luverne",
    "Russellville",
    "Winfield"
];

const result = findMissing(googleCitiesO, FAcitiesO);
console.log(`Missing from arry2: ${result.missingFromArr2}\n`);
console.log(`Missing from arry1: ${result.missingFromArr1}`);
