function findMissing(arr1, arr2) {
    const set1 = new Set(arr1);
    const set2 = new Set(arr2);

    const missingFromArr2 = arr1.filter(item => !set2.has(item));
    const missingFromArr1 = arr2.filter(item => !set1.has(item));

    return {
        missingFromArr2,
        missingFromArr1
    };
};

const FAcitiesO = [
    'Alameda',
    'Alhambra',
    'Anaheim',
    'Antioch',
    'Arcadia',
    'Bakersfield',
    'Barstow',
    'Belmont',
    'Berkeley',
    'Beverly Hills',
    'Brea',
    'Buena Park',
    'Burbank',
    'Calexico',
    'Calistoga',
    'Carlsbad',
    'Carmel',
    'Chico',
    'Chula Vista',
    'Claremont',
    'Compton',
    'Concord',
    'Corona',
    'Coronado',
    'Costa Mesa',
    'Culver City',
    'Daly City',
    'Davis',
    'Downey',
    'El Centro',
    'El Cerrito',
    'El Monte',
    'Escondido',
    'Eureka',
    'Fairfield',
    'Fontana',
    'Fremont',
    'Fresno',
    'Fullerton',
    'Garden Grove',
    'Glendale',
    'Hayward',
    'Hollywood',
    'Huntington Beach',
    'Indio',
    'Inglewood',
    'Irvine',
    'La Habra',
    'Laguna Beach',
    'Lancaster',
    'Livermore',
    'Lodi',
    'Lompoc',
    'Long Beach',
    'Los Angeles',
    'Malibu',
    'Martinez',
    'Marysville',
    'Menlo Park',
    'Merced',
    'Modesto',
    'Monterey',
    'Mountain View',
    'Napa',
    'Needles',
    'Newport Beach',
    'Norwalk',
    'Novato',
    'Oakland',
    'Oceanside',
    'Ojai',
    'Ontario',
    'Orange',
    'Oroville',
    'Oxnard',
    'Pacific Grove',
    'Palm Springs',
    'Palmdale',
    'Palo Alto',
    'Pasadena',
    'Petaluma',
    'Pomona',
    'Port Hueneme',
    'Rancho Cucamonga',
    'Red Bluff',
    'Redding',
    'Redlands',
    'Redondo Beach',
    'Redwood City',
    'Richmond',
    'Riverside',
    'Roseville',
    'Sacramento',
    'Salinas',
    'San Bernardino',
    'San Clemente',
    'San Diego',
    'San Fernando',
    'San Francisco',
    'San Gabriel',
    'San Jose',
    'San Juan Capistrano',
    'San Leandro',
    'San Luis Obispo',
    'San Marino',
    'San Mateo',
    'San Pedro',
    'San Rafael',
    'San Simeon',
    'Santa Ana',
    'Santa Barbara',
    'Santa Clara',
    'Santa Clarita',
    'Santa Cruz',
    'Santa Monica',
    'Santa Rosa',
    'Sausalito',
    'Simi Valley',
    'Sonoma',
    'South San Francisco',
    'Stockton',
    'Sunnyvale',
    'Susanville',
    'Thousand Oaks',
    'Torrance',
    'Turlock',
    'Ukiah',
    'Vallejo',
    'Ventura',
    'Victorville',
    'Visalia',
    'Walnut Creek',
    'Watts',
    'West Covina',
    'Whittier',
    'Woodland',
    'Yorba Linda',
    'Yuba City',
];

const googleCitiesO = [
    "Los Angeles",
    "San Diego",
    "San Jose",
    "San Francisco",
    "Fresno",
    "Sacramento",
    "Long Beach",
    "Oakland",
    "Bakersfield",
    "Anaheim",
    "Santa Ana",
    "Riverside",
    "Stockton",
    "Chula Vista",
    "Irvine",
    "Fremont",
    "San Bernardino",
    "Modesto",
    "Oxnard",
    "Fontana",
    "Moreno Valley",
    "Huntington Beach",
    "Glendale",
    "Santa Clarita",
    "Garden Grove",
    "Oceanside",
    "Rancho Cucamonga",
    "Santa Rosa",
    "Ontario",
    "Lancaster",
    "Elk Grove",
    "Corona",
    "Palmdale",
    "Salinas",
    "Pomona",
    "Hayward",
    "Escondido",
    "Torrance",
    "Sunnyvale",
    "Pasadena",
    "Orange",
    "Fullerton",
    "Thousand Oaks",
    "Visalia",
    "Simi Valley",
    "Concord",
    "Roseville",
    "Victorville",
    "Santa Clara",
    "Vallejo",
    "Berkeley",
    "El Monte",
    "Downey",
    "Costa Mesa",
    "Inglewood",
    "Carlsbad",
    "San Buenaventura (Ventura)",
    "Fairfield",
    "West Covina",
    "Murrieta",
    "Richmond",
    "Norwalk",
    "Antioch",
    "Temecula",
    "Burbank",
    "Daly City",
    "Rialto",
    "Santa Maria",
    "El Cajon",
    "San Mateo",
    "Clovis",
    "Compton",
    "Jurupa Valley",
    "Vista",
    "South Gate",
    "Mission Viejo",
    "Vacaville",
    "Carson",
    "Hesperia",
    "Santa Monica",
    "Westminster",
    "Redding",
    "Santa Barbara",
    "Chico",
    "Newport Beach",
    "San Leandro",
    "San Marcos",
    "Whittier",
    "Hawthorne",
    "Citrus Heights",
    "Tracy",
    "Alhambra",
    "Livermore",
    "Buena Park",
    "Menifee",
    "Hemet",
    "Lakewood",
    "Merced",
    "Chino",
    "Indio",
    "Redwood City",
    "Lake Forest",
    "Napa",
    "Tustin",
    "Bellflower",
    "Mountain View",
    "Chino Hills",
    "Baldwin Park",
    "Alameda",
    "Upland",
    "Folsom",
    "San Ramon",
    "Pleasanton",
    "Lynwood",
    "Union City",
    "Apple Valley",
    "Redlands",
    "Turlock",
    "Perris",
    "Manteca",
    "Milpitas",
    "Redondo Beach",
    "Davis",
    "Camarillo",
    "Yuba City",
    "Rancho Cordova",
    "Palo Alto",
    "Yorba Linda",
    "Walnut Creek",
    "Chico",
    "San Clemente",
    "Laguna Niguel",
    "Pico Rivera",
    "Montebello",
    "Lodi",
    "Madera",
    "Santa Cruz",
    "La Habra",
    "Encinitas",
    "Monterey Park",
    "Tulare",
    "Cupertino",
    "Gardena",
    "National City",
    "Rocklin",
    "Petaluma",
    "Huntington Park",
    "San Rafael",
    "La Mesa",
    "Arcadia",
    "Fountain Valley",
    "Diamond Bar",
    "Woodland",
    "Santee",
    "Lake Elsinore",
    "Porterville",
    "Paramount",
    "Eastvale",
    "Rosemead",
    "Hanford",
    "Highland",
    "Brentwood",
    "Novato",
    "Colton",
    "Cathedral City",
    "Delano",
    "Yucaipa",
    "Watsonville",
    "Placentia",
    "Glendora",
    "Gilroy",
    "Palm Desert",
    "Cerritos",
    "West Sacramento",
    "Aliso Viejo",
    "Poway",
    "La Mirada",
    "Rancho Santa Margarita",
    "Cypress",
    "Dublin",
    "Covina",
    "Azusa",
    "Palm Springs",
    "San Luis Obispo",
    "Ceres",
    "San Jacinto",
    "Lincoln",
    "Newark",
    "Lompoc",
    "El Centro",
    "Danville",
    "Bell Gardens",
    "Coachella",
    "Rancho Palos Verdes",
    "San Bruno",
    "Rohnert Park",
    "Brea",
    "La Puente",
    "Campbell",
    "San Gabriel",
    "Beaumont",
    "Morgan Hill",
    "Culver City",
    "Calexico",
    "Stanton",
    "La Quinta",
    "Pacifica",
    "Montclair",
    "Oakley",
    "Monrovia",
    "Los Banos",
    "Martinez"
];

const result = findMissing(googleCitiesO, FAcitiesO);
console.log(`Missing from arry2: ${result.missingFromArr2}\n`);
console.log(`Missing from arry1: ${result.missingFromArr1}`);
