function findMissing(arr1, arr2) {
    const set1 = new Set(arr1);
    const set2 = new Set(arr2);

    const missingFromArr2 = arr1.filter(item => !set2.has(item));
    const missingFromArr1 = arr2.filter(item => !set1.has(item));

    return {
        missingFromArr2,
        missingFromArr1
    };
};

const FAcitiesO = [
   'Aberdeen',
    'Anacortes',
    'Auburn',
    'Bellevue',
    'Bellingham',
    'Bremerton',
    'Centralia',
    'Coulee Dam',
    'Coupeville',
    'Ellensburg',
    'Ephrata',
    'Everett',
    'Hoquiam',
    'Kelso',
    'Kennewick',
    'Longview',
    'Moses Lake',
    'Oak Harbor',
    'Olympia',
    'Pasco',
    'Point Roberts',
    'Port Angeles',
    'Pullman',
    'Puyallup',
    'Redmond',
    'Renton',
    'Richland',
    'Seattle',
    'Spokane',
    'Tacoma',
    'Vancouver',
    'Walla Walla',
    'Wenatchee',
    'Yakima',
];

const googleCitiesO = [
   "Seattle",
    "Spokane",
    "Tacoma",
    "Vancouver",
    "Bellevue",
    "Kent",
    "Everett",
    "Renton",
    "Yakima",
    "Federal Way",
    "Spokane Valley",
    "Bellingham",
    "Kennewick",
    "Auburn",
    "Pasco",
    "Marysville",
    "Lakewood",
    "Redmond",
    "Shoreline",
    "Richland",
    "Kirkland",
    "Burien",
    "Sammamish",
    "Olympia",
    "Lacey",
    "Edmonds",
    "Bremerton",
    "Puyallup",
    "Longview",
    "Lynnwood",
    "Issaquah",
    "Mount Vernon",
    "Wenatchee",
    "University Place",
    "Parkland",
    "Pullman",
    "Des Moines",
    "SeaTac",
    "Maple Valley",
    "Mercer Island",
    "Moses Lake",
    "Spanaway",
    "Oak Harbor",
    "Camas",
    "Bothell",
    "Walla Walla",
    "Lake Stevens",
    "Kenmore",
    "Mukilteo",
    "Bonney Lake",
    "Mountlake Terrace",
    "Arlington",
    "Tumwater",
    "Battle Ground",
    "Monroe",
    "Centralia",
    "Washougal",
    "Sunnyside",
    "Kelso",
    "Anacortes",
    "Covington",
    "Bainbridge Island",
    "Lake Forest Park",
    "Shelton",
    "Port Angeles",
    "Burlington",
    "Port Orchard",
    "Sedro-Woolley",
    "Ferndale",
    "Enumclaw",
    "Clarkston",
    "West Richland",
    "Edgewood",
    "Orting",
    "Ellensburg",
    "Snoqualmie",
    "Snohomish",
    "Milton",
    "Gig Harbor",
    "Granite Falls",
    "Othello",
    "Cheney",
    "Newcastle",
    "Ridgefield",
    "Poulsbo",
    "Stanwood",
    "Woodinville",
    "Yelm"
];

const result = findMissing(googleCitiesO, FAcitiesO);
console.log(`Missing from arry2: ${result.missingFromArr2}\n`);
console.log(`Missing from arry1: ${result.missingFromArr1}`);
