// import {flatten} from 'lodash';

export const Countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "The Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "The Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sudan, South",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const CountryRegions: Record<string, string[]> = {
  Canada: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon Territory",
  ],
  "United States": [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Federated States of Micronesia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Palau",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virgin Island",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
};

export const Regions = flatten(Object.values(CountryRegions));

export const CanadaRegionCitiesMap: Record<string, string[]> = {
  Alberta: [
    "Airdrie",
    "Banff",
    "Beaumont",
    "Bonnyville",
    "Brazeau",
    "Breton",
    "Brooks",
    "Calgary",
    "Camrose",
    "Chestermere",
    "Cold Lake",
    "Canmore",
    "Didzbury",
    "Drayton Valley",
    "Edmonton",
    "Fort Saskatchewan",
    "Fort McMurray",
    "Ft. Saskatchewan",
    "Grande Prairie",
    "Hanna",
    "Hinton",
    "Irricana",
    "Jasper",
    "Lacombe",
    "Lake Louise",
    "Leduc",
    "Lethbridge",
    "Lloydminster",
    "McLennan",
    "Medicine Hat",
    "Olds",
    "Onoway",
    "Provost",
    "Red Deer",
    "Saint Albert",
    "Spruce Grove",
    "St. Albert",
    "Strathcona County",
    "Strathmore",
    "Swan Hills",
    "Sylvan Lake",
    "Taber",
    "Turner Valley",
    "Vermillion",
    "Wood Buffalo",
    "Wetaskiwin",
  ],
  "British Columbia": [
    "Abbotsford",
    "Armstrong",
    "Barkerville",
    "Burnaby",
    "Cache Creek",
    "Campbell River",
    "Castlegar",
    "Chemainus",
    "Chilliwack",
    "City of Port Moody",
    "Clearwater",
    "Colwood",
    "Coquitlam",
    "Courtenay",
    "Cranbrook",
    "Dawson Creek",
    "Delta",
    "Duncan",
    "Enderby",
    "Esquimalt",
    "Fernie",
    "Fort Saint James",
    "Fort Saint John",
    "Grand Forks",
    "Greenwood",
    "Hope",
    "Invermere",
    "Kamloops",
    "Kaslo",
    "Kelowna",
    "Kimberley",
    "Kitimat",
    "Langley",
    "Langford",
    "Lumby",
    "Maple Ridge",
    "Merritt",
    "Mission",
    "Nanaimo",
    "Nelson",
    "New Westminster",
    "North Cowichan",
    "North Vancouver",
    "Oak Bay",
    "Osoyoos",
    "Parksville",
    "Peace River",
    "Penticton",
    "Port Alberni",
    "Port Hardy",
    "Port Coquitlam",
    "Port Moody",
    "Powell River",
    "Prince George",
    "Prince Rupert",
    "Pitt Meadows",
    "Quesnel",
    "Revelstoke",
    "Richmond",
    "Rossland",
    "Saanich",
    "Sooke",
    "Sparwood",
    "Surrey",
    "Salmon Arm",
    "Terrace",
    "Trail",
    "Tumbler",
    "Vancouver",
    "Vernon",
    "Victoria",
    "West Vancouver",
    "West Kelowna",
    "Williams Lake",
    "Whistler",
    "White Rock",
  ],
  Manitoba: [
    "Birtle",
    "Brandon",
    "Churchill",
    "Cranberry Portage",
    "Dauphin",
    "Flin Flon",
    "Kildonan",
    "Morden",
    "Portage la Prairie",
    "Saint Boniface",
    "Snow Lake",
    "Steinbach",
    "Stonewall",
    "Swan River",
    "Selkirk",
    "The Pas",
    "Thompson",
    "Winnipeg",
    "Winkler",
    "York Factory",
  ],
  "New Brunswick": [
    "Bathurst",
    "Cap-Pele",
    "Caraquet",
    "Campbellton",
    "Dieppe",
    "Dalhousie",
    "Edmundston",
    "Fredericton",
    "Grand Bay-Westfield",
    "Grand Falls",
    "Memramcook",
    "Miramichi",
    "Moncton",
    "Oromocto",
    "Port Elgin",
    "Sackville",
    "Saint John",
    "Saint Stephen",
    "Shippagan",
    "Sussex",
    "Tracadie-Sheila",
  ],
  "Newfoundland and Labrador": [
    "Argentia",
    "Burgeo",
    "Bishop's Falls",
    "Bonavista",
    "Botwood",
    "Brigus",
    "Bay Roberts",
    "Carbonear",
    "Clarenville",
    "Channel-Port aux Basques",
    "Corner Brook",
    "Conception Bay South",
    "Deer Lake",
    "Ferryland",
    "Fogo Island",
    "Gander",
    "Goulds",
    "Grand Falls–Windsor",
    "Happy Valley–Goose Bay",
    "Harbour Grace",
    "Humber Arm South",
    "Lumsden",
    "Labrador City",
    "Lewisporte",
    "Mount Pearl",
    "Marystown",
    "New-Wes-Valley",
    "Paradise",
    "Placentia",
    "Pouch Cove",
    "Portaux Basques",
    "Portugal Cove-St. Philip’s",
    "Petty Harbour-Maddox Cove",
    "Saint Anthony",
    "St. John's",
    "St. John’s",
    "Stephenville",
    "Springdale",
    "Summerford",
    "Torbay",
    "Twillingate",
    "Trinity Bay North",
    "Upper Island Cove",
    "Victoria",
    "Wabana",
    "Wabush",
    "Witless Bay",
  ],
  "Northwest Territories": [
    "Aklavik",
    "Behchokǫ̀",
    "Colville Lake",
    "Deline",
    "Enterprise",
    "Fort Smith",
    "Fort Simpson",
    "Fort McPherson",
    "Fort Resolution",
    "Fort Providence",
    "Gamètì",
    "Hay River",
    "Inuvik",
    "Jean Marie River",
    "Kakisa",
    "Lutselk’e",
    "Norman Wells",
    "Nahanni Butte",
    "Paulatuk",
    "Sachs Harbour",
    "Tulita",
    "Town of Hay River",
    "Town of Inuvik",
    "Tuktoyaktuk",
    "Tsiigehtchic",
    "Ulukhaktok",
    "Whati",
    "Wrigley",
    "Wekweeti",
    "Yellowknife",
  ],
  "Nova Scotia": [
    "Amherst",
    "Annapolis",
    "Argyle",
    "Antigonish",
    "Berwick",
    "Bedford",
    "Baddeck",
    "Bridgewater",
    "Cape Breton",
    "Chester",
    "Canso",
    "County of Kings",
    "Clark’s Harbour",
    "Cumberland County",
    "Digby",
    "Dartmouth",
    "East Hants",
    "Guysborough",
    "Glace Bay",
    "Halifax",
    "Hantsport",
    "Hants County",
    "Inverness",
    "Inverness County",
    "Kentville",
    "Liverpool",
    "Louisbourg",
    "Lunenburg",
    "Lunenburg County",
    "Mulgrave",
    "Middleton",
    "Mahone Bay",
    "New Glasgow",
    "New Minas",
    "Oxford",
    "Parrsboro",
    "Pictou",
    "Pictou County",
    "Port Hawkesbury",
    "Queens",
    "Richmond",
    "Stewiacke",
    "Shelburne",
    "Springhill",
    "Stellarton",
    "Sydney",
    "Truro",
    "Trenton",
    "Tatamagouche",
    "Windsor",
    "Wolfville",
    "Westville",
    "Weymouth",
    "Yarmouth",
  ],
  Nunavut: ["Iqaluit"],
  Ontario: [
    "Ajax",
    "Aurora",
    "Atikokan",
    "Bancroft",
    "Barrie",
    "Belleville",
    "Blandford-Blenheim",
    "Blind River",
    "Brampton",
    "Brant",
    "Brantford",
    "Brock",
    "Brockville",
    "Burlington",
    "Bracebridge",
    "Bradford West Gwillimbury",
    "Caledon",
    "Cambridge",
    "Chatham",
    "Chatham-Kent",
    "Chesterville",
    "Clarington",
    "Cobourg",
    "Cochrane",
    "Collingwood",
    "Cornwall",
    "Cumberland",
    "Deep River",
    "Dundas",
    "Durham",
    "Dymond",
    "Ear Falls",
    "East Gwillimbury",
    "East Zorra-Tavistock",
    "Elgin",
    "Elliot Lake",
    "Etobicoke",
    "Flamborough",
    "Fort Erie",
    "Fort Frances",
    "Gananoque",
    "Georgina",
    "Glanbrook",
    "Gloucester",
    "Goulbourn",
    "Gravenhurst",
    "Grimsby",
    "Guelph",
    "Greater Sudbury",
    "Haldimand-Norfork",
    "Halton",
    "Hawkesbury",
    "Halton Hills",
    "Hamilton",
    "Hamilton-Wentworth",
    "Hearst",
    "Huntsville",
    "Haldimand County",
    "Innisfil",
    "Ingersoll",
    "Iroquois Falls",
    "James",
    "Kanata",
    "Kapuskasing",
    "Kawartha Lakes",
    "Kenora",
    "Kincardine",
    "King",
    "Kingston",
    "Kirkland Lake",
    "Kitchener",
    "Larder Lake",
    "Laurentian Hills",
    "Leamington",
    "Lennox-Addington",
    "Lincoln",
    "Lindsay",
    "London",
    "Loyalist Township",
    "Markham",
    "Merrickville",
    "Metro Toronto",
    "Midland",
    "Milton",
    "Mississauga",
    "Moose Factory",
    "Moosonee",
    "Nepean",
    "Newmarket",
    "Niagara",
    "Niagara Falls",
    "Niagara-on-the-Lake",
    "North Bay",
    "Norfolk County",
    "North Dorchester",
    "North Dumfries",
    "North York",
    "Norwich",
    "Oakville",
    "Orangeville",
    "Orillia",
    "Osgoode",
    "Oshawa",
    "Ottawa",
    "Ottawa-Carleton",
    "Owen Sound",
    "Parry Sound",
    "Perth",
    "Peterborough",
    "Pickering",
    "Picton",
    "Port Bruce",
    "Port Burwell",
    "Port Colborne",
    "Port Hope",
    "Pembroke",
    "Prince Edward",
    "Quinte West",
    "Renfrew",
    "Richmond Hill",
    "Saint Catharines",
    "Saint Thomas",
    "Sarnia",
    "Sarnia-Clearwater",
    "Sault Sainte Marie",
    "Sault Ste. Marie",
    "Scarborough",
    "Scugog",
    "Simcoe",
    "Smiths Falls",
    "Souix Lookout CoC Sioux Lookout",
    "South-West Oxford",
    "St. Catharines",
    "St. Thomas",
    "Stoney Creek",
    "Stratford",
    "Sudbury",
    "Temagami",
    "Temiskaming Shores",
    "Thorold",
    "Thunder Bay",
    "Tillsonburg",
    "Timmins",
    "Toronto",
    "Trenton",
    "Uxbridge",
    "Vaughan",
    "Wainfleet",
    "Wasaga Beach",
    "Waterloo",
    "Welland",
    "Wellesley",
    "West Carleton",
    "West Lincoln",
    "West Nipissing",
    "Whitby",
    "Wilmot",
    "Windsor",
    "Woodstock",
    "Woolwich",
    "York",
  ],
  "Prince Edward Island": [
    "Alberton",
    "Borden",
    "Belfast",
    "Borden-Carleton",
    "Bedeque and Area",
    "Crapaud",
    "Cavendish",
    "Charlottetown",
    "Cornwall",
    "Georgetown",
    "Hunter River",
    "Kensington",
    "Montague",
    "Miscouche",
    "North Rustico",
    "O’Leary",
    "Souris",
    "Stratford",
    "Summerside",
    "Tignish",
    "Tyne Valley",
    "Wellington",
  ],
  Quebec: [
    "Alma",
    "Amos",
    "Anjou",
    "Asbestos",
    "Aylmer",
    "Baie-Comeau",
    "Beauport",
    "Becancour",
    "Beloeil",
    "Bromptonville",
    "Boisbriand",
    "Brosssard",
    "Blainville",
    "Cap-de-la-Madeleine",
    "Chambly",
    "Charlesbourg",
    "Chateauguay",
    "Chibougamau",
    "Chicoutimi",
    "Châteauguay",
    "Coaticook",
    "Côte-Saint-Luc",
    "Dorval",
    "Dollard-Des",
    "Drummondville",
    "Fleurimont",
    "Gaspe",
    "Gaspé",
    "Gatineau",
    "Granby",
    "Havre-Saint-Pierre",
    "Hull",
    "Joliette",
    "Jonquiere",
    "Jonquière",
    "Kuujjuaq",
    "La Salle",
    "La Tuque",
    "LaSalle",
    "Lachine",
    "Lasalle",
    "L’Assomption",
    "Laurentides",
    "Laval",
    "Lennoxville",
    "Levis",
    "Longueuil",
    "Lévis",
    "Magog",
    "Mirabel",
    "Marieville",
    "Mascouche",
    "Matane",
    "Montreal",
    "Montreal Region",
    "Montreal-Est",
    "Montréal-Nord",
    "Mount Royal",
    "Ormeaux",
    "Percé",
    "Port-Cartier",
    "Pointe-Claire",
    "Quebec",
    "Repentigny",
    "Rimouski",
    "Rouyn-Noranda",
    "Saguenay",
    "Shawinigan",
    "Saint-Georges",
    "Saint-Eustache",
    "Saint-Hubert",
    "Saint-Hyacinthe",
    "Saint-Leonard",
    "Saint-Jerome",
    "Saint-Constant",
    "Saint-Jean-sur-Richelieu",
    "Sainte-Anne-de-Beaupré",
    "Salaberry-de-Valleyfield",
    "Sainte-Marthe-sur-le-Lac",
    "Sainte-Foy",
    "Sainte-Thérèse",
    "Sainte-Julie",
    "Sept-Îles",
    "Sherbrooke",
    "Sorel",
    "Sorel-Tracy",
    "Terrebonne",
    "Thetford Mines",
    "Trois-Rivières",
    "Val-d’Or",
    "Vaudreuil-Dorion",
    "Victoriaville",
    "Waskaganish",
  ],
  Saskatchewan: [
    "Avonlea",
    "Batoche",
    "Colonsay",
    "Craik",
    "Creighton",
    "Cumberland House",
    "Eastend",
    "Esterhazy",
    "Estevan",
    "Flin Flon",
    "Gravelbourg",
    "Humboldt",
    "Lloydminster",
    "Melfort",
    "Melville",
    "Moose Jaw",
    "Meadow Lake",
    "Martensville",
    "Nipawin",
    "North Battleford",
    "Prince Albert",
    "Regina",
    "Saskatoon",
    "Shell Lake",
    "Swift Current",
    "Tisdale",
    "Unity",
    "Uranium City",
    "Warman",
    "Weyburn",
    "Wynyard",
    "Yorkton",
  ],
  Yukon: [
    "Beaver Creek",
    "Burwash Landing",
    "Carcross",
    "Carmacks",
    "Dawson City",
    "Destruction Bay",
    "Faro",
    "Haines Junction",
    "Mayo",
    "Old Crow",
    "Pelly Crossing",
    "Ross River",
    "Teslin",
    "Watson Lake",
    "Whitehorse",
  ],
};

export const CanadaCities = flatten(Object.values(CanadaRegionCitiesMap));

export const USRegionCitiesMap: Record<string, string[]> = {
  Alabama: [
    "Alexander City",
    "Andalusia",
    "Anniston",
    "Alabaster",
    "Albertville",
    "Athens",
    "Atmore",
    "Auburn",
    "Arab",
    "Ashland",
    "Attalla",
    "Brent",
    "Boaz",
    "Bessemer",
    "Bay Minette",
    "Birmingham",
    "Chickasaw",
    "Clanton",
    "Cullman",
    "Chelsea",
    "Childersburg",
    "Center Point",
    "Decatur",
    "Demopolis",
    "Dothan",
    "Daphne",
    "Daleville",
    "Enterprise",
    "Eufaula",
    "Evergreen",
    "Foley",
    "Fultondale",
    "Florence",
    "Fairhope",
    "Fairfield",
    "Fort Payne",
    "Geneva",
    "Gadsden",
    "Greenville",
    "Guntersville",
    "Gulf Shores",
    "Hoover",
    "Helena",
    "Hokes Bluff",
    "Hueytown",
    "Hartselle",
    "Hartford",
    "Headland",
    "Hamilton",
    "Homewood",
    "Huntsville",
    "Irondale",
    "Jasper",
    "Jacksonville",
    "Lanett",
    "Leeds",
    "Luverne",
    "LaFayette",
    "Livingston",
    "Marion",
    "Mobile",
    "Moody",
    "Madison",
    "Millbrook",
    "Monroeville",
    "Muscle Shoals",
    "Montgomery",
    "Mountain Brook",
    "Northport",
    "Opelika",
    "Ozark",
    "Oxford",
    "Oneonta",
    "Pelham",
    "Phenix City",
    "Piedmont",
    "Prichard",
    "Prattville",
    "Rainsville",
    "Red Bay",
    "Rainbow City",
    "Russellville",
    "Scottsboro",
    "Selma",
    "Satsuma",
    "Saraland",
    "Sheffield",
    "Sylacauga",
    "Talladega",
    "Trussville",
    "Troy",
    "Tuscaloosa",
    "Tuscumbia",
    "Tallassee",
    "Tuskegee",
    "Thomasville",
    "Union Springs",
    "Vestavia Hills",
    "Winfield",
  ],
  Alaska: [
    "Adak",
    "Akutan",
    "Anchorage",
    "Barrow",
    "Bethel",
    "Craig",
    "Cordova",
    "Dillingham",
    "Delta Junction",
    "Fairbanks",
    "Gustavus",
    "Haines",
    "Homer",
    "Houston",
    "Hoonah",
    "Juneau",
    "King Cove",
    "Ketchikan",
    "Kodiak",
    "Kenai",
    "Kotzebue",
    "Klawock",
    "Metlakatla",
    "Nome",
    "North Pole",
    "Palmer",
    "Petersburg",
    "Seward",
    "Soldotna",
    "Seldovia",
    "Sitka",
    "Togiak",
    "Skagway",
    "Sand Point",
    "Unalaska",
    "Valdez",
    "Wasilla",
    "Wrangell",
    "Whittier",
    "Yakutat",
  ],
  Arizona: [
    "Ajo",
    "Avondale",
    "Apache Junction",
    "Bisbee",
    "Buckeye",
    "Bullhead City",
    "Camp Verde",
    "Casa Grande",
    "Chandler",
    "Clifton",
    "Coolidge",
    "Colorado City",
    "Carefree",
    "Clarkdale",
    "Cave Creek",
    "Cottonwood",
    "Chino Valley",
    "Duncan",
    "Douglas",
    "Dewey-Humboldt",
    "Eloy",
    "Eagar",
    "El Mirage",
    "Flagstaff",
    "Florence",
    "Fredonia",
    "Fountain Hills",
    "Gila Bend",
    "Glendale",
    "Globe",
    "Gilbert",
    "Goodyear",
    "Hayden",
    "Huachuca City",
    "Kingman",
    "Kearny",
    "Litchfield Park",
    "Lake Havasu City",
    "Mesa",
    "Miami",
    "Marana",
    "Mammoth",
    "Maricopa",
    "Nogales",
    "Oraibi",
    "Oro Valley",
    "Page",
    "Parker",
    "Payson",
    "Peoria",
    "Pima",
    "Pinetop",
    "Phoenix",
    "Prescott",
    "Patagonia",
    "Prescott Valley",
    "Pinetop-Lakeside",
    "Quartzsite",
    "Queen Creek",
    "Red Rock",
    "Sells",
    "Safford",
    "Somerton",
    "Show Low",
    "Surprise",
    "Superior",
    "Scottsdale",
    "Sahuarita",
    "San Luis",
    "Sedona",
    "Springerville",
    "Snowflake",
    "Sierra Vista",
    "Star Valley",
    "St. Johns",
    "Thatcher",
    "Tempe",
    "Taylor",
    "Tolleson",
    "Tombstone",
    "Tucson",
    "Walpi",
    "Window Rock",
    "Winslow",
    "Williams",
    "Wellton",
    "Willcox",
    "Wickenburg",
    "Yuma",
    "Youngtown",
  ],
  Arkansas: [
    "Arkadelphia",
    "Arkansas Post",
    "Batesville",
    "Benton",
    "Beebe",
    "Bryant",
    "Bella Vista",
    "Blytheville",
    "Bentonville",
    "Cabot",
    "Camden",
    "Conway",
    "Crossett",
    "Clarksville",
    "El Dorado",
    "Fayetteville",
    "Forrest City",
    "Fort Smith",
    "Greenwood",
    "Harrison",
    "Helena",
    "Hope",
    "Hot Springs",
    "Heber Springs",
    "Helena-West Helena",
    "Jacksonville",
    "Jonesboro",
    "Little Rock",
    "Mena",
    "Marion",
    "Malvern",
    "Magnolia",
    "Morrilton",
    "Maumelle",
    "Monticello",
    "Mountain Home",
    "Newport",
    "North Little Rock",
    "Osceola",
    "Paragould",
    "Pocahontas",
    "Pine Bluff",
    "Rogers",
    "Russellville",
    "Searcy",
    "Sherwood",
    "Stuttgart",
    "Springdale",
    "Siloam Springs",
    "Trumann",
    "Texarkana",
    "Van Buren",
    "Wynne",
    "West Memphis",
  ],
  California: [
    "Azusa",
    "Alameda",
    "Alhambra",
    "Anaheim",
    "Antioch",
    "Arcadia",
    "Aliso Viejo",
    "Apple Valley",
    "Bakersfield",
    "Barstow",
    "Belmont",
    "Beaumont",
    "Berkeley",
    "Beverly Hills",
    "Baldwin Park",
    "Brea",
    "Bellflower",
    "Bell Gardens",
    "Buena Park",
    "Brentwood",
    "Burbank",
    "Calexico",
    "Covina",
    "Calistoga",
    "Campbell",
    "Carlsbad",
    "Cypress",
    "Carson",
    "Ceres",
    "Carmel",
    "Chico",
    "Chino",
    "Clovis",
    "Colton",
    "Cupertino",
    "Camarillo",
    "Cerritos",
    "Coachella",
    "Chino Hills",
    "Cathedral City",
    "Citrus Heights",
    "Chula Vista",
    "Claremont",
    "Compton",
    "Concord",
    "Corona",
    "Coronado",
    "Costa Mesa",
    "Culver City",
    "Daly City",
    "Davis",
    "Dublin",
    "Downey",
    "Danville",
    "Delano",
    "Diamond Bar",
    "Elk Grove",
    "El Centro",
    "El Cerrito",
    "El Monte",
    "El Cajon",
    "Escondido",
    "Encinitas",
    "Eureka",
    "Eastvale",
    "Fairfield",
    "Fontana",
    "Folsom",
    "Fremont",
    "Fresno",
    "Fullerton",
    "Fountain Valley",
    "Garden Grove",
    "Gilroy",
    "Glendale",
    "Glendora",
    "Gardena",
    "Hemet",
    "Hanford",
    "Hesperia",
    "Highland",
    "Hawthorne",
    "Hayward",
    "Hollywood",
    "Huntington Beach",
    "Huntington Park",
    "Indio",
    "Inglewood",
    "Irvine",
    "Jurupa Valley",
    "Lynwood",
    "La Habra",
    "La Mesa",
    "La Puente",
    "Laguna Beach",
    "Laguna Niguel",
    "Lancaster",
    "Livermore",
    "Lodi",
    "Lakewood",
    "Lompoc",
    "Lincoln",
    "Long Beach",
    "Los Angeles",
    "Los Banos",
    "Lake Forest",
    "Lake Elsinore",
    "La Mirada",
    "La Quinta",
    "Malibu",
    "Milpitas",
    "Manteca",
    "Madera",
    "Martinez",
    "Marysville",
    "Menlo Park",
    "Merced",
    "Modesto",
    "Monterey",
    "Montclair",
    "Monrovia",
    "Montebello",
    "Murrieta",
    "Menifee",
    "Morgan Hill",
    "Mission Viejo",
    "Monterey Park",
    "Moreno Valley",
    "Mountain View",
    "Napa",
    "Newark",
    "Needles",
    "National City",
    "Newport Beach",
    "Norwalk",
    "Novato",
    "Oakland",
    "Oceanside",
    "Ojai",
    "Ontario",
    "Oakley",
    "Orange",
    "Oroville",
    "Oxnard",
    "Perris",
    "Poway",
    "Pico Rivera",
    "Pacific Grove",
    "Pacifica",
    "Palm Springs",
    "Palm Desert",
    "Palmdale",
    "Paramount",
    "Palo Alto",
    "Pasadena",
    "Placentia",
    "Petaluma",
    "Pomona",
    "Porterville",
    "Pleasanton",
    "Port Hueneme",
    "Rancho Cucamonga",
    "Rancho Cordova",
    "Red Bluff",
    "Rialto",
    "Rosemead",
    "Redding",
    "Redlands",
    "Rohnert Park",
    "Rancho Santa Margarita",
    "Rancho Palos Verdes",
    "Redondo Beach",
    "Redwood City",
    "Richmond",
    "Riverside",
    "Roseville",
    "Rocklin",
    "Sacramento",
    "Salinas",
    "Santee",
    "Santa Maria",
    "San Bernardino",
    "San Clemente",
    "San Diego",
    "San Fernando",
    "San Francisco",
    "San Gabriel",
    "San Jose",
    "San Bruno",
    "San Juan Capistrano",
    "San Buenaventura (Ventura)",
    "San Leandro",
    "San Luis Obispo",
    "San Marino",
    "San Marcos",
    "San Mateo",
    "San Pedro",
    "San Rafael",
    "San Simeon",
    "San Ramon",
    "Santa Ana",
    "Santa Barbara",
    "Santa Clara",
    "Santa Clarita",
    "Santa Cruz",
    "Santa Monica",
    "Santa Rosa",
    "Sausalito",
    "Stanton",
    "San Jacinto",
    "Simi Valley",
    "Sonoma",
    "South Gate",
    "South San Francisco",
    "Stockton",
    "Sunnyvale",
    "Susanville",
    "Tracy",
    "Tulare",
    "Thousand Oaks",
    "Torrance",
    "Temecula",
    "Turlock",
    "Tustin",
    "Ukiah",
    "Upland",
    "Union City",
    "Vallejo",
    "Ventura",
    "Vacaville",
    "Victorville",
    "Visalia",
    "Vista",
    "Walnut Creek",
    "Watts",
    "West Covina",
    "Whittier",
    "Woodland",
    "Westminster",
    "Watsonville",
    "West Sacramento",
    "Yorba Linda",
    "Yuba City",
    "Yucaipa",
  ],
  Colorado: [
    "Alamosa",
    "Aspen",
    "Aurora",
    "Arvada",
    "Boulder",
    "Brush",
    "Berthoud",
    "Broomfield",
    "Breckenridge",
    "Buena Vista",
    "Brighton",
    "Carbondale",
    "Castle Rock",
    "Canon City",
    "Central City",
    "Climax",
    "Craig",
    "Commerce City",
    "Colorado Springs",
    "Cortez",
    "Cripple Creek",
    "Denver",
    "Delta",
    "Durango",
    "Dacono",
    "Erie",
    "Evans",
    "Eaton",
    "Englewood",
    "Estes Park",
    "Frederick",
    "Fountain",
    "Fruita",
    "Florence",
    "Firestone",
    "Fort Collins",
    "Fort Morgan",
    "Georgetown",
    "Glenwood Springs",
    "Golden",
    "Gypsum",
    "Greenwood Village",
    "Grand Junction",
    "Greeley",
    "Gunnison",
    "Johnstown",
    "Kersey",
    "Louisville",
    "Lafayette",
    "Lakewood",
    "La Junta",
    "Leadville",
    "Littleton",
    "Longmont",
    "Lone Tree",
    "Loveland",
    "Mead",
    "Montrose",
    "Milliken",
    "Manitou Springs",
    "Northglenn",
    "Ouray",
    "Parker",
    "Pagosa Springs",
    "Pueblo",
    "Rifle",
    "Salida",
    "Sheridan",
    "Silverton",
    "Steamboat Springs",
    "Sterling",
    "Telluride",
    "Trinidad",
    "Thornton",
    "Vail",
    "Windsor",
    "Wheat Ridge",
    "Walsenburg",
    "Wellington",
    "Westminster",
    "Woodland Park",
  ],
  Connecticut: [
    "Ansonia",
    "Avon",
    "Ashford",
    "Berlin",
    "Brooklyn",
    "Bloomfield",
    "Branford",
    "Bridgeport",
    "Burlington",
    "Brookfield",
    "Bristol",
    "Bethel",
    "Canton",
    "Coventry",
    "Clinton",
    "Chaplin",
    "Cheshire",
    "Colchester",
    "Canterbury",
    "Danbury",
    "Darien",
    "Derby",
    "Ellington",
    "Eastford",
    "East Lyme",
    "East Hartford",
    "East Hampton",
    "East Haven",
    "Enfield",
    "Fairfield",
    "Farmington",
    "Greenwich",
    "Groton Long Point",
    "Groton",
    "Guilford",
    "Granby",
    "Griswold",
    "Glastonbury",
    "Hamden",
    "Hampton",
    "Hebron",
    "Hartford",
    "Killingly",
    "Lebanon",
    "Lyme",
    "Lisbon",
    "Ledyard",
    "Litchfield",
    "Manchester",
    "Mansfield",
    "Meriden",
    "Marlborough",
    "Montville",
    "Middletown",
    "Mansfield Center",
    "Milford",
    "Madison",
    "Monroe",
    "Mystic",
    "Newtown",
    "Naugatuck",
    "Newington",
    "New Britain",
    "New Haven",
    "New London",
    "North Haven",
    "North Branford",
    "Norwalk",
    "Norwich",
    "Oxford",
    "Old Lyme",
    "Old Saybrook",
    "Orange",
    "Putnam",
    "Plainville",
    "Plainfield",
    "Redding",
    "Rocky Hill",
    "Ridgefield",
    "Seymour",
    "Storrs",
    "Sprague",
    "Shelton",
    "Somers",
    "Stafford",
    "Scotland",
    "Simsbury",
    "Southbury",
    "Southington",
    "South Windsor",
    "Stamford",
    "Stonington",
    "Stratford",
    "Tolland",
    "Trumbull",
    "Torrington",
    "Union",
    "Vernon",
    "Voluntown",
    "Wallingford",
    "Waterbury",
    "Waterford",
    "Watertown",
    "West Hartford",
    "West Haven",
    "Westport",
    "Wethersfield",
    "Willimantic",
    "Windham",
    "Woodbury",
    "Wilton",
    "Windsor",
    "Windsor Locks",
    "Winsted",
  ],
  Delaware: [
    "Dover",
    "Elsmere",
    "Georgetown",
    "Harrington",
    "Lewes",
    "Laurel",
    "Milford",
    "Millsboro",
    "Middletown",
    "New Castle",
    "Newark",
    "Rehoboth Beach",
    "Smyrna",
    "Seaford",
    "Wilmington",
  ],
  Florida: [
    "Aventura",
    "Apopka",
    "Apalachicola",
    "Altamonte Springs",
    "Bartow",
    "Belle Glade",
    "Boca Raton",
    "Bonita Springs",
    "Boynton Beach",
    "Bradenton",
    "Cape Coral",
    "Clermont",
    "Clearwater",
    "Casselberry",
    "Cocoa Beach",
    "Coconut Creek",
    "Coral Springs",
    "Cutler Bay",
    "Cooper City",
    "Cocoa-Rockledge",
    "Coral Gables",
    "Daytona Beach",
    "De Land",
    "Dunedin",
    "Doral",
    "Davie",
    "Deltona",
    "Dania Beach",
    "Deerfield Beach",
    "Delray Beach",
    "Edgewater",
    "Fernandina Beach",
    "Fort Lauderdale",
    "Fort Myers",
    "Fort Pierce",
    "Fort Walton Beach",
    "Gainesville",
    "Greenacres",
    "Hallandale Beach",
    "Hialeah",
    "Hollywood",
    "Homestead",
    "Haines City",
    "Jupiter",
    "Jacksonville",
    "Key West",
    "Kissimmee",
    "Lake City",
    "Lake Wales",
    "Lakeland",
    "Largo",
    "Lake Mary",
    "Lake Worth Beach",
    "Lauderhill",
    "Melbourne",
    "Miami",
    "Miami Gardens",
    "Miramar",
    "Margate",
    "Miami Beach",
    "Naples",
    "North Miami",
    "North Port",
    "North Lauderdale",
    "North Miami Beach",
    "New Smyrna Beach",
    "Ocala",
    "Ocoee",
    "Orlando",
    "Oakland Park",
    "Ormond Beach",
    "Palatka",
    "Pinellas Park",
    "Palmetto",
    "Plantation",
    "Palm Bay",
    "Plant City",
    "Parkland",
    "Palm Beach",
    "Palm Coast",
    "Panama City",
    "Pensacola",
    "Pompano Beach",
    "Palm Beach Gardens",
    "Pembroke Pines",
    "Port St. Lucie",
    "Port Orange",
    "Rockledge",
    "Saint Augustine",
    "Saint Petersburg",
    "St. Cloud",
    "Stuart",
    "Sanford",
    "Sarasota",
    "Sebring",
    "Sunrise",
    "Tamarac",
    "Tallahassee",
    "Tampa",
    "Tarpon Springs",
    "Titusville",
    "Venice",
    "Weston",
    "Wellington",
    "West Palm Beach",
    "Winter Springs",
    "White Springs",
    "Winter Garden",
    "Winter Haven",
    "Winter Park",
    "Zephyrhills",
  ],
  Georgia: [
    "Albany",
    "Americus",
    "Alpharetta",
    "Andersonville",
    "Athens",
    "Acworth",
    "Atlanta",
    "Augusta",
    "Buford",
    "Barnesville",
    "Bainbridge",
    "Blairsville",
    "Brunswick",
    "Clarkston",
    "Cairo",
    "Commerce",
    "Canton",
    "Conyers",
    "Chamblee",
    "Covington",
    "Cordele",
    "Camilla",
    "Calhoun",
    "Carrollton",
    "Cedartown",
    "Columbus",
    "Cartersville",
    "College Park",
    "Dahlonega",
    "Dalton",
    "Dublin",
    "Dallas",
    "Duluth",
    "Darien",
    "Decatur",
    "Dunwoody",
    "Douglasville",
    "Douglas",
    "Ellijay",
    "Eastman",
    "East Point",
    "Fairburn",
    "Fitzgerald",
    "Fayetteville",
    "Fort Valley",
    "Forest Park",
    "Gainesville",
    "Griffin",
    "Hinesville",
    "Jesup",
    "Johns Creek",
    "Kennesaw",
    "Kingsland",
    "Lilburn",
    "Loganville",
    "La Grange",
    "Lawrenceville",
    "Macon",
    "Milton",
    "Morrow",
    "Monroe",
    "Moultrie",
    "Marietta",
    "Milledgeville",
    "McDonough",
    "Newnan",
    "Norcross",
    "Plains",
    "Perry",
    "Pooler",
    "Powder Springs",
    "Peachtree City",
    "Rome",
    "Riverdale",
    "Roswell",
    "Smyrna",
    "Swainsboro",
    "Suwanee",
    "Snellville",
    "St. Marys",
    "Stockbridge",
    "Statesboro",
    "Savannah",
    "Sandy Springs",
    "Tifton",
    "Toccoa",
    "Tucker",
    "Thomasville",
    "Union City",
    "Vidalia",
    "Valdosta",
    "Villa Rica",
    "Winder",
    "Woodstock",
    "Warm Springs",
    "Warner Robins",
    "Washington",
    "Waycross",
  ],
  Hawaii: [
    "Aiea",
    "Ewa Beach",
    "Ewa Gentry",
    "Hanalei",
    "Halawa",
    "Hilo",
    "Hana",
    "Honaunau",
    "Honolulu",
    "Holualoa",
    "Hickam Housing",
    "Haiku-Pauwela",
    "Hawaiian Paradise Park",
    "Kailua",
    "Kahaluu",
    "Kula",
    "Kahului",
    "Kapolei",
    "Kaneohe",
    "Kihei",
    "Kapaa",
    "Kawaihae",
    "Kailua-Kona",
    "Lahaina",
    "Laie",
    "Lihue",
    "Lanai City",
    "Makakilo",
    "Mililani Mauka",
    "Mililani Town",
    "Nanakuli",
    "Pukalani",
    "Pearl City",
    "Schofield Barracks",
    "Waipahu",
    "Waianae",
    "Wahiawa",
    "Wailuku",
    "Waimea",
  ],
  Idaho: [
    "Ammon",
    "American Falls",
    "Blackfoot",
    "Boise",
    "Buhl",
    "Burley",
    "Bonners Ferry",
    "Chubbuck",
    "Caldwell",
    "Coeur d’Alene",
    "Eagle",
    "Emmett",
    "Fruitland",
    "Gooding",
    "Garden City",
    "Grangeville",
    "Hailey",
    "Hayden",
    "Idaho City",
    "Idaho Falls",
    "Jerome",
    "Kuna",
    "Ketchum",
    "Kellogg",
    "Lewiston",
    "Middleton",
    "Moscow",
    "Meridian",
    "Mountain Home",
    "Nampa",
    "Orofino",
    "Payette",
    "Pocatello",
    "Priest River",
    "Post Falls",
    "Preston",
    "Rupert",
    "Rexburg",
    "Rathdrum",
    "Star",
    "Shelley",
    "Sun Valley",
    "Sandpoint",
    "Twin Falls",
    "Weiser",
  ],
  Illinois: [
    "Alton",
    "Addison",
    "Arlington Heights",
    "Arthur",
    "Aurora",
    "Berwyn",
    "Belleville",
    "Bartlett",
    "Belvidere",
    "Buffalo Grove",
    "Bolingbrook",
    "Bloomington",
    "Brookfield",
    "Cahokia",
    "Cairo",
    "Calumet City",
    "Canton",
    "Carbondale",
    "Carlinville",
    "Carol Stream",
    "Carthage",
    "Centralia",
    "Champaign",
    "Charleston",
    "Chester",
    "Chicago",
    "Crystal Lake",
    "Carpentersville",
    "Chicago Heights",
    "Cicero",
    "Collinsville",
    "Danville",
    "Decatur",
    "DeKalb",
    "Des Plaines",
    "Downers Grove",
    "Dixon",
    "East Moline",
    "East Saint Louis",
    "Effingham",
    "Elgin",
    "Elmhurst",
    "Evanston",
    "Freeport",
    "Galena",
    "Galesburg",
    "Glen Ellyn",
    "Glenview",
    "Granite City",
    "Harrisburg",
    "Herrin",
    "Hanover Park",
    "Highland Park",
    "Hoffman Estates",
    "Jacksonville",
    "Joliet",
    "Kankakee",
    "Kaskaskia",
    "Kewanee",
    "La Salle",
    "Lake Forest",
    "Libertyville",
    "Lincoln",
    "Lisle",
    "Lombard",
    "Macomb",
    "Mattoon",
    "Moline",
    "Monmouth",
    "Mount Prospect",
    "Mount Vernon",
    "Mundelein",
    "Naperville",
    "Nauvoo",
    "Normal",
    "North Chicago",
    "Oak Park",
    "Oak Lawn",
    "Oregon",
    "Ottawa",
    "Orland Park",
    "Palatine",
    "Park Forest",
    "Park Ridge",
    "Pekin",
    "Peoria",
    "Petersburg",
    "Pontiac",
    "Plainfield",
    "Quincy",
    "Rantoul",
    "Romeoville",
    "River Forest",
    "Rock Island",
    "Rockford",
    "Salem",
    "Streamwood",
    "Shawneetown",
    "Skokie",
    "Schaumburg",
    "South Holland",
    "Springfield",
    "Streator",
    "Summit",
    "Tinley Park",
    "Urbana",
    "Vandalia",
    "Virden",
    "Waukegan",
    "Wheaton",
    "Wilmette",
    "Winnetka",
    "Wood River",
    "Wheeling",
    "Zion",
  ],
  Indiana: [
    "Avon",
    "Anderson",
    "Bedford",
    "Brownsburg",
    "Bloomington",
    "Carmel",
    "Columbus",
    "Connersville",
    "Corydon",
    "Crown Point",
    "Clarksville",
    "Crawfordsville",
    "Dyer",
    "East Chicago",
    "Elkhart",
    "Elwood",
    "Evansville",
    "Fishers",
    "Franklin",
    "Fort Wayne",
    "French Lick",
    "Gary",
    "Granger",
    "Greenwood",
    "Geneva",
    "Goshen",
    "Greenfield",
    "Highland",
    "Hammond",
    "Hobart",
    "Huntington",
    "Indianapolis",
    "Jeffersonville",
    "Kokomo",
    "Lawrence",
    "Lafayette",
    "Logansport",
    "Madison",
    "Marion",
    "Merrillville",
    "Michigan City",
    "Mishawaka",
    "Muncie",
    "Munster",
    "Noblesville",
    "Nappanee",
    "Nashville",
    "New Albany",
    "New Castle",
    "New Harmony",
    "Peru",
    "Portage",
    "Plymouth",
    "Plainfield",
    "Richmond",
    "St. John",
    "Seymour",
    "Santa Claus",
    "Shelbyville",
    "South Bend",
    "Schererville",
    "Terre Haute",
    "Valparaiso",
    "Vincennes",
    "Westfield",
    "Wabash",
    "West Lafayette",
    "Zionsville",
  ],
  Iowa: [
    "Adel",
    "Amana Colonies",
    "Ankeny",
    "Altoona",
    "Atlantic",
    "Algona",
    "Ames",
    "Boone",
    "Bondurant",
    "Belle Plaine",
    "Bettendorf",
    "Burlington",
    "Carroll",
    "Clear Lake",
    "Cedar Falls",
    "Cedar Rapids",
    "Charles City",
    "Cherokee",
    "Coralville",
    "Clinton",
    "Creston",
    "Clive",
    "Clarinda",
    "Council Bluffs",
    "Decorah",
    "Denison",
    "Davenport",
    "Des Moines",
    "Dubuque",
    "Eldridge",
    "Estherville",
    "Fairfield",
    "Forest City",
    "Fort Dodge",
    "Fort Madison",
    "Grinnell",
    "Glenwood",
    "Harlan",
    "Humboldt",
    "Hiawatha",
    "Independence",
    "Indianola",
    "Iowa City",
    "Johnston",
    "Keokuk",
    "Knoxville",
    "Le Mars",
    "Mason City",
    "Manchester",
    "Marshalltown",
    "Mount Pleasant",
    "Muscatine",
    "Maquoketa",
    "Marion",
    "Nevada",
    "Norwalk",
    "Newton",
    "North Liberty",
    "Osage",
    "Orange City",
    "Oskaloosa",
    "Ottumwa",
    "Pella",
    "Perry",
    "Red Oak",
    "Sheldon",
    "Sibley",
    "Spencer",
    "Sergeant Bluff",
    "Sioux City",
    "Storm Lake",
    "Spirit Lake",
    "Tipton",
    "Urbandale",
    "Vinton",
    "Waverly",
    "Walcott",
    "Washington",
    "Waukee",
    "Waterloo",
    "Winterset",
    "Webster City",
    "West Des Moines",
  ],
  Kansas: [
    "Abilene",
    "Arkansas City",
    "Atchison",
    "Bonner Springs",
    "Chanute",
    "Coffeyville",
    "Concordia",
    "Council Grove",
    "Derby",
    "Dodge City",
    "Emporia",
    "El Dorado",
    "Fort Scott",
    "Gardner",
    "Garden City",
    "Great Bend",
    "Hays",
    "Haysville",
    "Hutchinson",
    "Independence",
    "Junction City",
    "Kansas City",
    "Lawrence",
    "Leavenworth",
    "Liberal",
    "Lenexa",
    "Leawood",
    "Mission",
    "Merriam",
    "Manhattan",
    "McPherson",
    "Medicine Lodge",
    "Newton",
    "Olathe",
    "Osawatomie",
    "Ottawa",
    "Overland Park",
    "Parsons",
    "Pittsburg",
    "Prairie Village",
    "Salina",
    "Shawnee",
    "Smith Center",
    "Topeka",
    "Wichita",
    "Winfield",
    "Wellington",
  ],
  Kentucky: [
    "Ashland",
    "Alexandria",
    "Barbourville",
    "Bellevue",
    "Bardstown",
    "Berea",
    "Boonesborough",
    "Bowling Green",
    "Corbin",
    "Cynthiana",
    "Cold Spring",
    "Campbellsville",
    "Covington",
    "Danville",
    "Erlanger",
    "Elizabethtown",
    "Frankfort",
    "Florence",
    "Fort Mitchell",
    "Fort Thomas",
    "Glasgow",
    "Georgetown",
    "Harlan",
    "Hillview",
    "Harrodsburg",
    "Hazard",
    "Henderson",
    "Hodgenville",
    "Hopkinsville",
    "Independence",
    "Jeffersontown",
    "Lyndon",
    "Lawrenceburg",
    "Lexington",
    "Louisville",
    "Murray",
    "Mayfield",
    "Maysville",
    "Madisonville",
    "Middlesboro",
    "Mount Washington",
    "Newport",
    "Nicholasville",
    "Owensboro",
    "Paducah",
    "Paris",
    "Radcliff",
    "Richmond",
    "Shively",
    "Southgate",
    "Somerset",
    "Shelbyville",
    "St. Matthews",
    "Shepherdsville",
    "Versailles",
    "Villa Hills",
    "Winchester",
  ],
  Louisiana: [
    "Abbeville",
    "Alexandria",
    "Baker",
    "Bastrop",
    "Baton Rouge",
    "Bayou Cane",
    "Bogalusa",
    "Bossier City",
    "Breaux Bridge",
    "Carencro",
    "Central",
    "Crowley",
    "DeRidder",
    "Donaldsonville",
    "Eunice",
    "Estelle",
    "Franklin",
    "Grambling",
    "Gretna",
    "Hammond",
    "Harvery",
    "Houma",
    "Jennings",
    "kenner",
    "Lafayette",
    "Lapplace",
    "Leesville",
    "Lake Charles",
    "Luling",
    "Mandeville",
    "Marksville",
    "Marrero",
    "Metairie",
    "Minden",
    "Monroe",
    "Morgan City",
    "Natchitoches",
    "New Iberia",
    "New Orleans",
    "Opelousas",
    "Pineville",
    "Plaquemine",
    "Port Allen",
    "Rayne",
    "Ruston",
    "Saint Martinville",
    "Slidell",
    "Shreveport",
    "Saint Gabriel",
    "Sulphur",
    "Terrytown",
    "Thibodaux",
    "Walker",
    "Westwego",
    "West Monroe",
    "Winnifield",
    "Vidalia",
    "Ville Platte",
    "Youngsville",
    "Zachary",
  ],
  Maine: [
    "Auburn",
    "Augusta",
    "Bangor",
    "Bar Harbor",
    "Bath",
    "Belfast",
    "Bethel",
    "Biddeford",
    "Boothbay Harbor",
    "Brewer",
    "Brunswick",
    "Bucksport",
    "Calais",
    "Camden",
    "Caribou",
    "Castine",
    "Damariscotta",
    "Dexter",
    "Eastport",
    "Ellsworth",
    "Falmouth",
    "Farmington",
    "Freeport",
    "Fryeburg",
    "Fort Kent",
    "Gardiner",
    "Gray",
    "Greenville",
    "Hallowell",
    "Houlton",
    "Kennebunk",
    "Kennebunkport",
    "Kittery",
    "Lewiston",
    "Lisbon",
    "Lincoln",
    "Lubec",
    "Machias",
    "Madison",
    "Mechanic Falls",
    "Milford",
    "Newport",
    "Oakland",
    "Old Orchard Beach",
    "Old Town",
    "Orono",
    "Paris",
    "Poland",
    "Portland",
    "Presque Isle",
    "Rangeley",
    "Richmond",
    "Rockland",
    "Rumford",
    "Saco",
    "Sanford",
    "Scarborough",
    "Skowhegan",
    "South Portland",
    "Topsham",
    "Van Buren",
    "Waterville",
    "Wells",
    "Westbrook",
    "Windham",
    "Winslow",
    "Wiscasset",
    "winthrop",
    "Yarmouth",
    "York",
  ],
  Maryland: [
    "Aberdeen",
    "Annapolis",
    "Baltimore",
    "Bethesda",
    "Bethesda-Chevy Chase",
    "Bowie",
    "Cambridge",
    "Catonsville",
    "College Park",
    "Columbia",
    "Cumberland",
    "Easton",
    "Elkton",
    "Emmitsburg",
    "Frederick",
    "Gaithersburg",
    "Greenbelt",
    "Hagerstown",
    "Hyattsville",
    "Laurel",
    "Oakland",
    "Ocean City",
    "Rockville",
    "Saint Marys City",
    "Salisbury",
    "Silver Spring",
    "Takoma Park",
    "Towson",
    "Westminster",
  ],
  Massachusetts: [
    "Abington",
    "Adams",
    "Amesbury",
    "Amherst",
    "Andover",
    "Arlington",
    "Athol",
    "Attleboro",
    "Barnstable Town",
    "Bedford",
    "Beverly",
    "Boston",
    "Bourne",
    "Braintree Town",
    "Brockton",
    "Brookline",
    "Cambridge",
    "Canton",
    "Charlestown",
    "Chelmsford",
    "Chelsea",
    "Chicopee",
    "Clinton",
    "Cohasset",
    "Concord",
    "Danvers",
    "Dartmouth",
    "Dedham",
    "Dennis",
    "Duxbury",
    "Eastham",
    "Edgartown",
    "Everett",
    "Fairhaven",
    "Fall River",
    "Falmouth",
    "Fitchburg",
    "Framingham",
    "Gloucester",
    "Great Barrington",
    "Greenfield",
    "Groton",
    "Harwich",
    "Haverhill",
    "Hingham",
    "Holyoke",
    "Hyannis",
    "Ipswich",
    "Lawrence",
    "Lenox",
    "Leominster",
    "Lexington",
    "Lowell",
    "Ludlow",
    "Lynn",
    "Malden",
    "Marblehead",
    "Marlborough",
    "Medford",
    "Methuen",
    "Milton",
    "Nahant",
    "Natick",
    "New Bedford",
    "Newburyport",
    "Newton",
    "North Adams",
    "Northampton",
    "Norton",
    "Norwood",
    "Peabody",
    "Pittsfield",
    "Plymouth",
    "Provincetown",
    "Quincy",
    "Randolph",
    "Revere",
    "Salem",
    "Sandwich",
    "Saugus",
    "Somerville",
    "South Hadley",
    "Springfield",
    "Stockbridge",
    "Stoughton",
    "Sturbridge",
    "Sudbury",
    "Taunton",
    "Tewksbury",
    "Truro",
    "Waltham",
    "Watertown",
    "Webster",
    "Wellesley",
    "Wellfleet",
    "West Bridgewater",
    "West Springfield",
    "Westfield",
    "Weymouth Town",
    "Whitman",
    "Williamstown",
    "Woburn",
    "Woods Hole",
    "Worcester",
  ],
  Michigan: [
    "Adrian",
    "Alma",
    "Ann Arbor",
    "Battle Creek",
    "Bay City",
    "Benton Harbor",
    "Bloomfield Hills",
    "Cadillac",
    "Charlevoix",
    "Cheboygan",
    "Dearborn",
    "Detroit",
    "East Lansing",
    "Eastpointe",
    "Ecorse",
    "Escanaba",
    "Farmington Hills",
    "Flint",
    "Grand Haven",
    "Grand Rapids",
    "Grayling",
    "Grosse Pointe",
    "Hancock",
    "Highland Park",
    "Holland",
    "Houghton",
    "Interlochen",
    "Iron Mountain",
    "Ironwood",
    "Ishpeming",
    "Jackson",
    "Kalamazoo",
    "Lansing",
    "Livonia",
    "Ludington",
    "Mackinaw City",
    "Manistee",
    "Marquette",
    "Menominee",
    "Midland",
    "Monroe",
    "Mount Clemens",
    "Mount Pleasant",
    "Muskegon",
    "Niles",
    "Petoskey",
    "Pontiac",
    "Port Huron",
    "Rochester Hills",
    "Royal Oak",
    "Saginaw",
    "saint Clair Shores",
    "Saint Ignace",
    "Saint Joseph",
    "Sault Sainte Marie",
    "Southfield",
    "Sterling Heights",
    "Taylor",
    "Traverse City",
    "Trenton",
    "Troy",
    "Warren",
    "Westland",
    "Wyandotte",
    "Wyoming",
    "Ypsilanti",
  ],
  Minnesota: [
    "Albert Lea",
    "Alexandria",
    "Andover",
    "Apple Valley",
    "Austin",
    "Bemidji",
    "Blaine",
    "Bloomington",
    "Brainerd",
    "Brooklyn Center",
    "Brooklyn Park",
    "Burnsville",
    "Coon Rapids",
    "Cottage Grove",
    "Crookston",
    "Duluth",
    "Eagan",
    "Eden Prairie",
    "Edina",
    "Ely",
    "Eveleth",
    "Faribault",
    "Fergus Falls",
    "Hastings",
    "Hibbing",
    "International Falls",
    "Inver Grove Heights",
    "Lakeville",
    "Little Falls",
    "Mankato",
    "Maple Grove",
    "Minneapolis",
    "Minnetonka",
    "Moorhead",
    "New Ulm",
    "Northfield",
    "Oakdale",
    "Owatonna",
    "Pipestone",
    "Plymouth",
    "Red Wing",
    "Rochester",
    "Roseville",
    "Saint Cloud",
    "saint Louis Park",
    "Saint Paul",
    "Sauk Centre",
    "Savage",
    "Shakopee",
    "South Saint Paul",
    "Stillwater",
    "Virginia",
    "Willmar",
    "Winona",
    "Woodbury",
  ],
  Mississippi: [
    "Bay Saint Louis",
    "Biloxi",
    "Brandon",
    "Canton",
    "Clarksdale",
    "Clinton",
    "Columbia",
    "Columbus",
    "Corinth",
    "Greenville",
    "Greenwood",
    "Grenada",
    "Gulfport",
    "Hattiesburg",
    "Holly Springs",
    "Horn lake",
    "Jackson",
    "Laurel",
    "Madison",
    "Meridian",
    "Natchez",
    "Ocean Springs",
    "Olive Branch",
    "Oxford",
    "Pascagoula",
    "Pass Christian",
    "Pearl",
    "Philadelphia",
    "Port Gibson",
    "Ridgeland",
    "Southaven",
    "Starkville",
    "Tupelo",
    "Vicksburg",
    "West Point",
    "Yazoo City",
  ],
  Missouri: [
    "Ballwin",
    "Blue Springs",
    "Boonville",
    "Branson",
    "Cape Girardeau",
    "Carthage",
    "Chesterfield",
    "Chillicothe",
    "Clayton",
    "Columbia",
    "Excelsior Springs",
    "Ferguson",
    "Florissant",
    "Fulton",
    "Hannibal",
    "Independence",
    "Jefferson City",
    "Joplin",
    "Kansas City",
    "Kirksville",
    "Lamar",
    "Lebanon",
    "Lee´s Summit",
    "Lexington",
    "Maryville",
    "Mexico",
    "Monett",
    "Neosho",
    "New Madrid",
    "o´Fallon",
    "Raytown",
    "Rolla",
    "Saint Charles",
    "Saint Joseph",
    "Saint Louis",
    "Sainte Genevieve",
    "Salem",
    "Sedalia",
    "Springfield",
    "University City",
    "Warrensburg",
    "Wentzville",
    "West Plains",
    "Wildwood",
  ],
  Montana: [
    "Anaconda",
    "Belgrade",
    "Billings",
    "Bozeman",
    "Butte",
    "Columbia Falls",
    "Dillon",
    "Fort Benton",
    "Glendive",
    "Great Falls",
    "Hamilton",
    "Havre",
    "Helena",
    "Kalispell",
    "Laurel",
    "Lewistown",
    "Livingston",
    "Miles City",
    "Missoula",
    "Polson",
    "Sidney",
    "Virginia City",
    "Whitefish",
  ],
  Nebraska: [
    "Alliance",
    "Beatrice",
    "Bellevue",
    "Blair",
    "Boys Town",
    "Chadron",
    "Columbus",
    "Fremont",
    "Gering",
    "Grand Island",
    "Hastings",
    "Kearney",
    "La Vista",
    "Lexington",
    "Lincoln",
    "McCook",
    "Minden",
    "Nebraska City",
    "Norfolk",
    "North Platte",
    "Omaha",
    "Papillion",
    "Plattsmouth",
    "Red Cloud",
    "Scottsbluff",
    "Sidney",
    "South Sioux City",
    "York",
  ],
  Nevada: [
    "Boulder City",
    "Caliente",
    "Carlin",
    "Carson City",
    "Elko",
    "Ely",
    "Fallon",
    "Fernley",
    "Genoa",
    "Goldfield",
    "Henderson",
    "Las Vegas",
    "Lovelock",
    "Mesquite",
    "North Las Vegas",
    "Reno",
    "Sparks",
    "Virginia City",
    "Wells",
    "West Wendover",
    "Winnemucca",
    "Yerington",
  ],
  "New Hampshire": [
    "Bedford",
    "Berlin",
    "Claremont",
    "Concord",
    "Derry",
    "Dover",
    "Durham",
    "Exeter",
    "Franklin",
    "Goffstown",
    "Hampton",
    "Hanover",
    "Hillsborough",
    "Hooksett",
    "Hudson",
    "Keene",
    "Laconia",
    "Lebanon",
    "Londonderry",
    "Manchester",
    "Merrimack",
    "Milford",
    "Nashua",
    "Peterborough",
    "Plymouth",
    "Portsmouth",
    "Rochester",
    "Salem",
    "Somersworth",
    "Windham",
  ],
  "New Jersey": [
    "Asbury Park",
    "Atlantic City",
    "Bayonne",
    "Bloomfield",
    "Bordentown",
    "Bound Brook",
    "Brick",
    "Bridgeton",
    "Burlington",
    "Caldwell",
    "Cherry Hill",
    "Camden",
    "Cape May",
    "Clifton",
    "Cranford",
    "East Orange",
    "Edison",
    "Elizabeth",
    "Englewood",
    "Fort Lee",
    "Franklin",
    "Glassboro",
    "Gloucester",
    "Hackensack",
    "Haddonfield",
    "Hamilton",
    "Hoboken",
    "Irvington",
    "Jackson",
    "Jersey City",
    "Lakehurst",
    "Lakewood",
    "Long Beach",
    "Long Branch",
    "Madison",
    "Menlo Park",
    "Millburn",
    "Millville",
    "Montclair",
    "Morristown",
    "Mount Holly",
    "New Brunswick",
    "New Milford",
    "Newark",
    "North Bergen",
    "Ocean City",
    "Old Bridge",
    "Orange",
    "Parsippany–Troy Hills",
    "Passaic",
    "Paterson",
    "Perth Amboy",
    "Piscataway",
    "Plainfield",
    "Princeton",
    "Ridgewood",
    "Roselle",
    "Rutherford",
    "Salem",
    "Somerville",
    "South Orange Village",
    "Toms River",
    "Totowa",
    "Trenton",
    "Union",
    "Union City",
    "Vineland",
    "Wayne",
    "Weehawken",
    "West New York",
    "West Orange",
    "Willingboro",
    "Woodbridge",
  ],
  "New Mexico": [
    "Acoma",
    "Alamogordo",
    "Albuquerque",
    "Artesia",
    "Belen",
    "Carlsbad",
    "Clovis",
    "Deming",
    "Espanola",
    "Farmington",
    "Gallup",
    "Grants",
    "Hobbs",
    "Las Cruces",
    "Las Vegas",
    "Los Alamos",
    "Los Lunas",
    "Lovington",
    "Portales",
    "Raton",
    "Rio Rancho",
    "Roswell",
    "Santa Fe",
    "Shiprock",
    "Silver City",
    "Socorro",
    "Sunland Park",
    "Taos",
    "Truth or Consequences",
    "Tucumcari",
  ],
  "New York": [
    "Albany",
    "Amsterdam",
    "Auburn",
    "Babylon",
    "Batavia",
    "Beacon",
    "Bedford",
    "Binghamton",
    "Bronx",
    "Brooklyn",
    "Buffalo",
    "Chautauqua",
    "Cheektowaga",
    "Clinton",
    "Cohoes",
    "Coney Island",
    "Cooperstown",
    "Corning",
    "Cortland",
    "Crown Point",
    "Dunkirk",
    "East Aurora",
    "East Hampton",
    "Eastchester",
    "Elmira",
    "Flushing",
    "Forest Hills",
    "Fredonia",
    "Freeport",
    "Garden City",
    "Geneva",
    "Glens Falls",
    "Gloversville",
    "Great Neck",
    "Hammondsport",
    "Harlem",
    "Hempstead",
    "Herkimer",
    "Hudson",
    "Huntington",
    "Hyde Park",
    "Ilion",
    "Ithaca",
    "Jamestown",
    "Johnstown",
    "Kingston",
    "Lackawanna",
    "Lake Placid",
    "Levittown",
    "Lockport",
    "Mamaroneck",
    "Manhattan",
    "Massena",
    "Middletown",
    "Mineola",
    "Mount Vernon",
    "New Paltz",
    "New Rochelle",
    "New Windsor",
    "New York City",
    "Newburgh",
    "Niagara Falls",
    "North Hempstead",
    "Nyack",
    "Ogdensburg",
    "Olean",
    "Oneida",
    "Oneonta",
    "Ossining",
    "Oswego",
    "Oyster Bay",
    "Palmyra",
    "Peekskill",
    "Plattsburgh",
    "Port Washington",
    "Potsdam",
    "Poughkeepsie",
    "Queens",
    "Rensselaer",
    "Rochester",
    "Rome",
    "Rotterdam",
    "Rye",
    "Sag Harbor",
    "Saranac Lake",
    "Saratoga Springs",
    "Scarsdale",
    "Schenectady",
    "Seneca Falls",
    "Southampton",
    "Staten Island",
    "Stony Brook",
    "Stony Point",
    "Syracuse",
    "Tarrytown",
    "Ticonderoga",
    "Tonawanda",
    "Troy",
    "Utica",
    "Valley stream",
    "Watertown",
    "Watervliet",
    "Watkins Glen",
    "West Seneca",
    "White Plains",
    "Woodstock",
    "Yonkers",
  ],
  "North Carolina": [
    "Asheboro",
    "Asheville",
    "Bath",
    "Beaufort",
    "Boone",
    "Burlington",
    "Cary",
    "Chapel Hill",
    "Charlotte",
    "Concord",
    "Durham",
    "Edenton",
    "Elizabeth City",
    "Fayetteville",
    "Gastonia",
    "Goldsboro",
    "Greensboro",
    "Greenville",
    "Halifax",
    "Henderson",
    "Hickory",
    "High Point",
    "Hillsborough",
    "Jacksonville",
    "Kinston",
    "Kitty Hawk",
    "Lumberton",
    "Morehead City",
    "Morganton",
    "Nags Head",
    "New Bern",
    "Pinehurst",
    "Raleigh",
    "Rocky Mount",
    "Salisbury",
    "Shelby",
    "Washington",
    "Wilmington",
    "Wilson",
    "Winston-Salem",
  ],
  "North Dakota": [
    "Bismarck",
    "Devils Lake",
    "Dickinson",
    "Fargo",
    "Grand Forks",
    "Jamestown",
    "Mandan",
    "Minot",
    "Rugby",
    "Valley City",
    "Wahpeton",
    "West Fargo",
    "Williston",
  ],
  Ohio: [
    "Akron",
    "Alliance",
    "Ashtabula",
    "Athens",
    "Austintown",
    "Barberton",
    "Beavercreek",
    "Bedford",
    "Beachwood",
    "Bellefontaine",
    "Bowling Green",
    "Brunswick",
    "Bucyrus",
    "Cambridge",
    "Canton",
    "Celina",
    "Chillicothe",
    "Cincinnati",
    "Circleville",
    "Cleveland",
    "Cleveland Heights",
    "Columbus",
    "Conneaut",
    "Coshocton",
    "Cuyahoga Falls",
    "Dayton",
    "Defiance",
    "Delaware",
    "Dublin",
    "East Cleveland",
    "East Liverpool",
    "Elyria",
    "Euclid",
    "Fairborn",
    "Fairfield",
    "Findlay",
    "Fremont",
    "Forest Park",
    "Gahanna",
    "Gallipolis",
    "Garfield Heights",
    "Green",
    "Greenville",
    "Grove City",
    "Hamilton",
    "Harrison",
    "Hilliard",
    "Huber Heights",
    "Kent",
    "Kettering",
    "Lakewood",
    "Lancaster",
    "Lima",
    "Lorain",
    "Mansfield",
    "Maple Heights",
    "Marietta",
    "Marion",
    "Martins Ferry",
    "Marysville",
    "Mason",
    "Massillon",
    "Maumee",
    "Medina",
    "Mentor",
    "Middletown",
    "Milan",
    "Mount Vernon",
    "New Philadelphia",
    "Newark",
    "Niles",
    "North College Hill",
    "North Olmsted",
    "North Royalton",
    "Norwalk",
    "Norwood",
    "Oberlin",
    "Oregon",
    "Oxford",
    "Painesville",
    "Parma",
    "Perry Township",
    "Piqua",
    "Portsmouth",
    "Put-in-Bay",
    "Ravenna",
    "Reynoldsburg",
    "Saint Marys",
    "Salem",
    "Sandusky",
    "Shaker Heights",
    "Sidney",
    "Springfield",
    "Steubenville",
    "Stow",
    "Strongsville",
    "Tiffin",
    "Toledo",
    "Troy",
    "Trotwood",
    "Upper Arlington",
    "Urbana",
    "Van Wert",
    "Wadsworth",
    "Wapakoneta",
    "Warren",
    "Westerville",
    "Westlake",
    "Willoughby",
    "Wooster",
    "Worthington",
    "Xenia",
    "Yellow Springs",
    "Youngstown",
    "Zanesville",
  ],
  Oklahoma: [
    "Ada",
    "Altus",
    "Alva",
    "Anadarko",
    "Ardmore",
    "Bartlesville",
    "Bethany",
    "Bixby",
    "Blackwell",
    "Blanchard",
    "Broken Arrow",
    "Chickasha",
    "Choctaw",
    "Claremore",
    "Clinton",
    "Cushing",
    "Del City",
    "Duncan",
    "Durant",
    "Edmond",
    "El Reno",
    "Elk City",
    "Enid",
    "Eufaula",
    "Frederick",
    "Glenpool",
    "Guthrie",
    "Guymon",
    "Hobart",
    "Holdenville",
    "Hugo",
    "Kingfisher",
    "Lawton",
    "McAlester",
    "Miami",
    "Midwest City",
    "Moore",
    "Muskogee",
    "Norman",
    "Oklahoma City",
    "Okmulgee",
    "Owasso",
    "Pauls Valley",
    "Pawhuska",
    "Perry",
    "Ponca City",
    "Poteau",
    "Pryor Creek",
    "Sallisaw",
    "Sand Springs",
    "Sapulpa",
    "Seminole",
    "Shawnee",
    "Stillwater",
    "Tahlequah",
    "The Village",
    "Tulsa",
    "Vinita",
    "Wagoner",
    "Warr Acres",
    "Wewoka",
    "Woodward",
    "Yukon",
  ],
  Oregon: [
    "Albany",
    "Ashland",
    "Astoria",
    "Baker City",
    "Beaverton",
    "Bend",
    "Boardman",
    "Brookings",
    "Burns",
    "Canby",
    "Central Point",
    "Coos Bay",
    "Corvallis",
    "Cottage Grove",
    "Dallas",
    "Eugene",
    "Florence",
    "Forest",
    "Gladstone",
    "Grants Pass",
    "Gresham",
    "Grove",
    "Happy Valley",
    "Hermiston",
    "Hillsboro",
    "Hood River",
    "Jacksonville",
    "John Day",
    "keizer",
    "Klamath Falls",
    "La Grande",
    "Lake Oswego",
    "Lakeview",
    "Lebanon",
    "Lincoln City",
    "McMinnville",
    "Medford",
    "Milwaukie",
    "Monmouth",
    "Newberg",
    "Newport",
    "Ontario",
    "Oregon City",
    "Pendleton",
    "Port Orford",
    "Portland",
    "Prineville",
    "Redmond",
    "Reedsport",
    "Roseburg",
    "Saint Helens",
    "Salem",
    "Sandy",
    "Scappoose",
    "Seaside",
    "Sherwood",
    "Silverton",
    "Springfield",
    "Sweet Home",
    "Talent",
    "The Dalles",
    "Tigard",
    "Tillamook",
    "Troutdale",
    "Tualatin",
    "Umatilla",
    "Waldport",
    "Warrenton",
    "West Linn",
    "Wilsonville",
    "Woodburn",
  ],
  Pennsylvania: [
    "Abington",
    "Aliquippa",
    "Allentown",
    "Altoona",
    "Ambridge",
    "Bedford",
    "Bethlehem",
    "Bloomsburg",
    "Bradford",
    "Bristol",
    "Carbondale",
    "Carlisle",
    "Chambersburg",
    "Chester",
    "Columbia",
    "Easton",
    "Erie",
    "Franklin",
    "Germantown",
    "Gettysburg",
    "Greensburg",
    "Hanover",
    "Harmony",
    "Harrisburg",
    "Hazleton",
    "Hershey",
    "Homestead",
    "Honesdale",
    "Indiana",
    "Jeannette",
    "Jim Thorpe",
    "Johnstown",
    "Lancaster",
    "Lebanon",
    "Levittown",
    "Lewistown",
    "Lock Haven",
    "Lower Southampton",
    "McKeesport",
    "Meadville",
    "Middletown",
    "Monroeville",
    "Nanticoke",
    "New Castle",
    "New Hope",
    "New Kensington",
    "Norristown",
    "Oil City",
    "Philadelphia",
    "Phoenixville",
    "Pittsburgh",
    "Pottstown",
    "Pottsville",
    "Reading",
    "Scranton",
    "Shamokin",
    "Sharon",
    "State College",
    "Stroudsburg",
    "Sunbury",
    "Swarthmore",
    "Tamaqua",
    "Titusville",
    "Uniontown",
    "Warren",
    "Washington",
    "West Chester",
    "Wilkes-Barre",
    "Williamsport",
    "York",
  ],
  "Rhode Island": [
    "Barrington",
    "Bristol",
    "Burrillville",
    "Central Falls",
    "Charlestown",
    "Coventry",
    "Cranston",
    "Cumberland",
    "East Greenwich",
    "East Providence",
    "Exeter",
    "Foster",
    "Glocester",
    "Hopkinton",
    "Jamestown",
    "Johnston",
    "Kingston",
    "Lincoln",
    "Little Compton",
    "Middletown",
    "Narragansett",
    "Newport",
    "New Shoreham",
    "North Kingstown",
    "North Providence",
    "Pawtucket",
    "Portsmouth",
    "Providence",
    "Richmond",
    "Scituate",
    "Smithfield",
    "South Kingstown",
    "Tiverton",
    "Warren",
    "Warwick",
    "Westerly",
    "West Greenwich",
    "West warwick",
    "Wickford",
    "Woonsocket",
  ],
  "South Carolina": [
    "Abbeville",
    "Aiken",
    "Anderson",
    "Beaufort",
    "Berea",
    "Bluffton",
    "Camden",
    "Cayce",
    "Charleston",
    "Clemson",
    "Columbia",
    "Conway",
    "Darlington",
    "Dentsville",
    "Easley",
    "Five Forks",
    "Florence",
    "Forest Acres",
    "Fort mill",
    "Gaffney",
    "Gantt",
    "Garden City",
    "Georgetown",
    "Goose Creek",
    "Greer",
    "Greenville",
    "Greenwood",
    "Hanahan",
    "Hartsville",
    "Hilton Head Island",
    "Irmo",
    "Ladson",
    "Lancaster",
    "Laurens",
    "Lexington",
    "Mauldin",
    "Moncks Corner",
    "Mount Pleasant",
    "Myrtle Beach",
    "Newberry",
    "North Augusta",
    "North Charleston",
    "Orangeburg",
    "Port Royal",
    "Red Hill",
    "Rock Hill",
    "Seneca",
    "Simpsonville",
    "Spartanburg",
    "Socastee",
    "Sumter",
    "Summerville",
    "Taylors",
    "Union",
    "West Columbia",
  ],
  "South Dakota": [
    "Aberdeen",
    "Belle Fourche",
    "Brandon",
    "Brookings",
    "Canton",
    "Custer",
    "De Smet",
    "Deadwood",
    "Hot Springs",
    "Huron",
    "Lead",
    "Madison",
    "Milbank",
    "Mitchell",
    "Mobridge",
    "Pierre",
    "Rapid City",
    "Sioux Falls",
    "Spearfish",
    "Sturgis",
    "Vermillion",
    "Watertown",
    "Yankton",
  ],
  Tennessee: [
    "Alcoa",
    "Athens",
    "Bartlett",
    "Brentwood",
    "Chattanooga",
    "Clarksville",
    "Cleveland",
    "Collierville",
    "Columbia",
    "Cookeville",
    "Dayton",
    "Elizabethton",
    "Franklin",
    "Gallatin",
    "Gatlinburg",
    "Germantown",
    "Greeneville",
    "Hendersonville",
    "Jackson",
    "Johnson City",
    "Jonesborough",
    "Kingsport",
    "Knoxville",
    "La Vergne",
    "Lebanon",
    "Maryville",
    "Memphis",
    "Morristown",
    "Murfreesboro",
    "Nashville",
    "Norris",
    "Oak Ridge",
    "Shelbyville",
    "Smyrna",
    "Spring Hill",
    "Tullahoma",
  ],
  Texas: [
    "Abilene",
    "Alpine",
    "Amarillo",
    "Arlington",
    "Austin",
    "Baytown",
    "Beaumont",
    "Big Spring",
    "Borger",
    "Brownsville",
    "Bryan",
    "Canyon",
    "Cleburne",
    "College Station",
    "Corpus Christi",
    "Crystal City",
    "Dallas",
    "Del Rio",
    "Denison",
    "Denton",
    "Eagle Pass",
    "Edinburg",
    "El Paso",
    "Frisco",
    "Fort Worth",
    "Freeport",
    "Galveston",
    "Garland",
    "Grand Prairie",
    "Goliad",
    "Greenville",
    "Harlingen",
    "Houston",
    "Huntsville",
    "Irving",
    "Johnson City",
    "Kilgore",
    "Killeen",
    "Kingsville",
    "Laredo",
    "Longview",
    "Lubbock",
    "Lufkin",
    "Marshall",
    "McAllen",
    "McKinney",
    "Mesquite",
    "Midland",
    "Mission",
    "Nacogdoches",
    "New Braunfels",
    "Odessa",
    "Orange",
    "Pampa",
    "Paris",
    "Pasadena",
    "Pecos",
    "Pharr",
    "Plainview",
    "Plano",
    "Port Arthur",
    "Port Lavaca",
    "Richardson",
    "San Angelo",
    "San Antonio",
    "San Felipe",
    "San Marcos",
    "Sherman",
    "Sweetwater",
    "Temple",
    "Texarkana",
    "Texas City",
    "Tyler",
    "Uvalde",
    "Victoria",
    "Waco",
    "Weatherford",
    "Wichita Falls",
    "Ysleta",
  ],
  Utah: [
    "Alta",
    "American Fork",
    "Bountiful",
    "Brigham City",
    "Cedar City",
    "Clearfield",
    "Delta",
    "Draper",
    "Fillmore",
    "Green River",
    "Heber City",
    "Kanab",
    "Layton",
    "Lehi",
    "Logan",
    "Manti",
    "Millcreek",
    "Moab",
    "Monticello",
    "Murray",
    "Nephi",
    "Ogden",
    "Orderville",
    "Orem",
    "Panguitch",
    "Park City",
    "Payson",
    "Pleasant Grove",
    "Price",
    "Provo",
    "Riverton",
    "Roy",
    "Saint George",
    "Salt Lake City",
    "Sandy",
    "South Jordan",
    "Spanish Fork",
    "Springville",
    "Tooele",
    "Vernal",
    "West Jordan",
    "West Valley City",
  ],
  Vermont: [
    "Barre",
    "Bellows Falls",
    "Bennington",
    "Brattleboro",
    "Burlington",
    "Essex Junction",
    "Killington",
    "Manchester",
    "Middlebury",
    "Montpelier",
    "Morrisville",
    "Newport",
    "Northfield",
    "Plymouth",
    "Rutland",
    "Saint Albans",
    "Saint Johnsbury",
    "Sharon",
    "South Burlington",
    "Springfield",
    "Waterbury",
    "Winooski",
  ],
  Virginia: [
    "Abingdon",
    "Alexandria",
    "Blacksburg",
    "Bristol",
    "Charlottesville",
    "Chesapeake",
    "Danville",
    "Fairfax",
    "Falls Church",
    "Fredericksburg",
    "Hampton",
    "Hanover",
    "Harrisonburg",
    "Hopewell",
    "Leesburg",
    "Lexington",
    "Lynchburg",
    "Manassas",
    "Martinsville",
    "New Market",
    "Newport News",
    "Norfolk",
    "Petersburg",
    "Portsmouth",
    "Reston",
    "Richmond",
    "Roanoke",
    "Staunton",
    "Suffolk",
    "Virginia Beach",
    "Waynesboro",
    "Williamsburg",
    "Winchester",
  ],
  Washington: [
    "Arlington",
    "Aberdeen",
    "Anacortes",
    "Auburn",
    "Bothell",
    "Burien",
    "Bellevue",
    "Burlington",
    "Battle Ground",
    "Bellingham",
    "Bremerton",
    "Bonney Lake",
    "Bainbridge Island",
    "Camas",
    "Cheney",
    "Centralia",
    "Clarkston",
    "Coulee Dam",
    "Covington",
    "Coupeville",
    "Des Moines",
    "Ellensburg",
    "Edgewood",
    "Ephrata",
    "Everett",
    "Edmonds",
    "Enumclaw",
    "Ferndale",
    "Federal Way",
    "Gig Harbor",
    "Granite Falls",
    "Hoquiam",
    "Issaquah",
    "Kirkland",
    "Kenmore",
    "Kent",
    "Kelso",
    "Kennewick",
    "Lacey",
    "Lake Stevens",
    "Lake Forest Park",
    "Lynnwood",
    "Lakewood",
    "Longview",
    "Marysville",
    "Mukilteo",
    "Milton",
    "Monroe",
    "Moses Lake",
    "Maple Valley",
    "Mercer Island",
    "Mount Vernon",
    "Mountlake Terrace",
    "Newcastle",
    "Oak Harbor",
    "Olympia",
    "Orting",
    "Othello",
    "Pasco",
    "Poulsbo",
    "Parkland",
    "Point Roberts",
    "Port Angeles",
    "Port Orchard",
    "Pullman",
    "Puyallup",
    "Redmond",
    "Ridgefield",
    "Renton",
    "Richland",
    "SeaTac",
    "Stanwood",
    "Shelton",
    "Seattle",
    "Spokane",
    "Snoqualmie",
    "Snohomish",
    "Shoreline",
    "Spanaway",
    "Sunnyside",
    "Sedro-Woolley",
    "Sammamish",
    "Tacoma",
    "Tumwater",
    "University Place",
    "Vancouver",
    "Woodinville",
    "Walla Walla",
    "Washougal",
    "Wenatchee",
    "West Richland",
    "Yelm",
    "Yakima",
  ],
  "West Virginia": [
    "Bath",
    "Beckley",
    "Bluefield",
    "Bridgeport",
    "Buckhannon",
    "Charles Town",
    "Charleston",
    "Clarksburg",
    "Dunbar",
    "Elkins",
    "Fairmont",
    "Grafton",
    "Harpers Ferry",
    "Hillsboro",
    "Hinton",
    "Huntington",
    "Keyser",
    "Lewisburg",
    "Logan",
    "Martinsburg",
    "Morgantown",
    "Moundsville",
    "New Martinsville",
    "Nitro",
    "Oak Hill",
    "Parkersburg",
    "Philippi",
    "Point Pleasant",
    "Princeton",
    "Romney",
    "saint Albans",
    "Shepherdstown",
    "South Charleston",
    "Summersville",
    "Vienna",
    "Weirton",
    "Welch",
    "Wellsburg",
    "Weston",
    "Wheeling",
    "White Sulphur Springs",
    "Williamson",
  ],
  Wisconsin: [
    "Appleton",
    "Ashland",
    "Baraboo",
    "Belmont",
    "Beloit",
    "Brookfield",
    "Eau Claire",
    "Fond du Lac",
    "Green Bay",
    "Greenfield",
    "Hayward",
    "Janesville",
    "Kenosha",
    "La Crosse",
    "Lake Geneva",
    "Madison",
    "Manitowoc",
    "Marinette",
    "Menasha",
    "Menomonee Falls",
    "Milwaukee",
    "Neenah",
    "New Berlin",
    "New Glarus",
    "Oconto",
    "Oshkosh",
    "Peshtigo",
    "Portage",
    "Prairie du Chien",
    "Racine",
    "Rhinelander",
    "Ripon",
    "Sheboygan",
    "Spring Green",
    "Stevens Point",
    "Sturgeon Bay",
    "Sun Prairie",
    "Superior",
    "Waukesha",
    "Wausau",
    "Wauwatosa",
    "West Allis",
    "West Bend",
    "Wisconsin Dells",
  ],
  Wyoming: [
    "Buffalo",
    "Casper",
    "Cheyenne",
    "Cody",
    "Douglas",
    "Evanston",
    "Gillette",
    "Green River",
    "Jackson",
    "Kemmerer",
    "Lander",
    "Laramie",
    "Newcastle",
    "Powell",
    "Rawlins",
    "Riverton",
    "Rock Springs",
    "Saratoga",
    "Sheridan",
    "Ten Sleep",
    "Thermopolis",
    "Torrington",
    "Worland",
    "Wheatland",
  ],
};

export const USCities = flatten(Object.values(USRegionCitiesMap));

export const Cities = [...CanadaCities, ...USCities];

export const CountryCities: Record<string, Record<string, string[]>> = {
  Canada: CanadaRegionCitiesMap,
  "United States": USRegionCitiesMap,
};
